server:
  port: 8080
spring:
  pj:
    datasource:
     url:               jdbc:mysql://localhost:3306/pj?useUnicode=true&characterEncoding=utf-8
     username:          root
     password:          root
     driverClassName: com.mysql.jdbc.Driver
  qj:
    datasource:
      url:               jdbc:mysql://localhost:3306/qj?useUnicode=true&characterEncoding=utf-8
      username:          root
      password:          root
      driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    com:
      wendy:
        springboot:
          multi:
            datasource:
              pj:
                dao: debug
              qj:
                dao: debug

